package com.example.order_exercise.security;

public enum Feature {
    CUSTOMER_FINDALL,
    CUSTOMER_FINDBYID,
    CUSTOMER_CREATE,
    ITEM_CREATE,
    ITEM_FINDBYID,
    ITEM_FINDALL,
    ORDER_BYID,
    ORDER_FINDALL,
    ORDER_OVERVIEW,
    ORDER_SAVETOUSERORDERS,
    ORDER_SEEUSERORDERS;


}
